services:
  dmarclyzer:
    image: ghcr.io/ivancarlosti/dmarclyzer:latest
    container_name: dmarclyzer_app
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
